openweathermap:
  api:
    key: 77d0c01278fe6e5958c42cd2c8c67913
    url: https://api.openweathermap.org/data/2.5/weather

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/forecast
    username: root
    password: 5404
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
